name: current_location_bloc
description: current location package with bloc and location
version: 1.0.1+2
publish_to: none

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.4
  location: ^5.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  very_good_analysis: ^3.0.1
